# Generated by Django 3.2.9 on 2021-11-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=32)),
                ('pub_date', models.DateField()),
                ('isbn', models.CharField(max_length=13)),
                ('n_pages', models.IntegerField()),
                ('cover_link', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=16)),
            ],
        ),
    ]
